/**
 * Technology Roadmap API
 * Delivers dynamic market relevance data and user practice stack.
 *
 * NOTE: The relevance structure is dynamic and data-driven (not hardcoded to 'trending').
 * It supports automated updating from real-time developer index, job market postings,
 * GitHub metrics, and industry survey APIs.
 */

export const TECH_CATEGORIES = [
  'All',
  'Programming',
  'Frontend',
  'Backend',
  'Database',
  'Cloud',
  'DevOps',
  'AI/ML',
  'Generative AI',
  'Data Engineering',
  'Cybersecurity',
]

export const RELEVANCE_FILTERS = [
  'All Relevance',
  'Surging Demand',
  'High Demand',
  'Industry Standard',
  'Emerging Frontier',
]

const MOCK_ALL_TECHNOLOGIES = [
  // ─── 1. PROGRAMMING ──────────────────────────────────────────
  {
    id: 'python',
    name: 'Python',
    category: 'Programming',
    relevance: {
      score: 98,
      status: 'Surging Demand',
      growth: '+38% YoY',
      openings: '280k+ global openings',
    },
    level: 'Beginner',
    prerequisites: ['Basic Computing Concepts', 'Logic & Problem Solving'],
    estimatedLearningTime: '6–8 weeks',
    careerRelevance: 'Dominant language for AI/ML, Data Engineering, backend microservices, and automation scripts.',
    relatedJobs: ['AI/ML Engineer', 'Python Backend Developer', 'Data Scientist', 'Automation Engineer'],
    skillsRequired: ['Syntax & Data Structures', 'OOP & Functional Programming', 'Decorators & Generators', 'Virtual Environments & Packaging'],
    projectSuggestions: [
      { title: 'Async Microservice API', desc: 'FastAPI service with redis caching and async database pooling.', complexity: 'Intermediate' },
      { title: 'Distributed Web Crawler', desc: 'Fault-tolerant scraper with rate-limiting and data cleansing pipeline.', complexity: 'Advanced' },
    ],
    interviewTopics: ['GIL (Global Interpreter Lock) mechanics', 'AsyncIO vs Multiprocessing', 'Generators & Memory Profiling', 'Metaclasses'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#38bdf8',
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    category: 'Programming',
    relevance: {
      score: 96,
      status: 'Industry Standard',
      growth: '+22% YoY',
      openings: '350k+ global openings',
    },
    level: 'Beginner',
    prerequisites: ['HTML & CSS Fundamentals', 'Basic Logic'],
    estimatedLearningTime: '6–10 weeks',
    careerRelevance: 'The foundational lingua franca of the web and dynamic server-side applications.',
    relatedJobs: ['Frontend Developer', 'Full Stack Developer', 'Node.js Backend Engineer'],
    skillsRequired: ['Event Loop & Microtasks', 'Closures & Scopes', 'Promises & Async/Await', 'ESNext Syntax & Prototypes'],
    projectSuggestions: [
      { title: 'Interactive State Management Engine', desc: 'Custom Redux/Zustand clone with publish-subscribe pattern.', complexity: 'Intermediate' },
      { title: 'Browser Canvas Game Engine', desc: '60fps collision detection and state loop in pure JavaScript.', complexity: 'Advanced' },
    ],
    interviewTopics: ['Event Loop and Call Stack execution order', 'Prototypal Inheritance', 'Scope Chaining & Hoisting', 'Debouncing & Throttling'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#facc15',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    category: 'Programming',
    relevance: {
      score: 97,
      status: 'Surging Demand',
      growth: '+44% YoY',
      openings: '240k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['Strong JavaScript (ES6+)', 'Understanding of Static Typing'],
    estimatedLearningTime: '4–6 weeks',
    careerRelevance: 'Mandatory standard in modern enterprise frontend and Node.js backend codebases.',
    relatedJobs: ['Senior Frontend Engineer', 'Full Stack Engineer', 'TypeScript Architect'],
    skillsRequired: ['Generics & Constraints', 'Union & Intersection Types', 'Conditional & Mapped Types', 'Type Narrowing & Guards'],
    projectSuggestions: [
      { title: 'Type-Safe RPC Client', desc: 'End-to-end type safety library between client and backend.', complexity: 'Advanced' },
      { title: 'Schema Validator & Parser', desc: 'Runtime validation library matching Zod with static inference.', complexity: 'Advanced' },
    ],
    interviewTopics: ['Conditional types and `infer` keyword', 'Structural typing vs Nominal typing', 'Keyof & Mapped types', 'Covariance and Contravariance'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#3b82f6',
  },
  {
    id: 'java',
    name: 'Java',
    category: 'Programming',
    relevance: {
      score: 91,
      status: 'Industry Standard',
      growth: '+14% YoY',
      openings: '290k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['Object-Oriented Programming principles', 'Data Structures & Algorithms'],
    estimatedLearningTime: '8–12 weeks',
    careerRelevance: 'The backbone of global banking, enterprise backends, and high-throughput transaction systems.',
    relatedJobs: ['Enterprise Java Developer', 'Backend Software Engineer', 'Fintech Platform Architect'],
    skillsRequired: ['JVM Memory Model & GC Tuning', 'Concurrency & Virtual Threads (Loom)', 'Streams & Lambda Expressions', 'Design Patterns'],
    projectSuggestions: [
      { title: 'High-Concurrency Order Matching Engine', desc: 'Stock exchange order book simulator processing 10k orders/sec.', complexity: 'Advanced' },
      { title: 'Multi-Tenant Banking Gateway', desc: 'Secure transactional API with idempotency and distributed tracing.', complexity: 'Intermediate' },
    ],
    interviewTopics: ['JVM Garbage Collection algorithms (G1, ZGC)', 'Virtual Threads vs OS Threads in Java 21', 'Synchronized vs Lock API', 'HashMap collision resolution'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#ea580c',
  },

  // ─── 2. FRONTEND ─────────────────────────────────────────────
  {
    id: 'react',
    name: 'React',
    category: 'Frontend',
    relevance: {
      score: 98,
      status: 'Industry Standard',
      growth: '+28% YoY',
      openings: '310k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['HTML5 & Modern CSS', 'ES6+ JavaScript', 'DOM Manipulation'],
    estimatedLearningTime: '6–8 weeks',
    careerRelevance: 'The most hired frontend UI library globally, essential for senior full-stack positions.',
    relatedJobs: ['Frontend Architect', 'React Engineer', 'UI/UX Technical Lead'],
    skillsRequired: ['Hooks & Custom Hooks', 'Concurrent Rendering & Suspense', 'React 19 Server Components & Actions', 'State Architecture'],
    projectSuggestions: [
      { title: 'Real-Time Collaboration Whiteboard', desc: 'Multiplayer canvas with WebSocket CRDT syncing.', complexity: 'Advanced' },
      { title: 'SaaS Analytics Dashboard', desc: 'Dynamic widgets, drag-and-drop layouts, and virtualized datasets.', complexity: 'Intermediate' },
    ],
    interviewTopics: ['Reconciliation & Fiber Architecture', 'React 19 Server Actions vs Client Components', 'useEffect dependency edge cases', 'Performance optimization (useMemo, memo, startTransition)'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#60a5fa',
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    category: 'Frontend',
    relevance: {
      score: 95,
      status: 'Surging Demand',
      growth: '+46% YoY',
      openings: '180k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['React', 'TypeScript', 'Web Routing & Server Basics'],
    estimatedLearningTime: '4–6 weeks',
    careerRelevance: 'Industry standard for modern production React applications with SSR, SSG, and edge routing.',
    relatedJobs: ['Next.js Developer', 'Full Stack React Engineer', 'Web Performance Engineer'],
    skillsRequired: ['App Router & Layouts', 'Server-Side Rendering (SSR) & Streaming', 'Caching & Revalidation strategies', 'Edge Middleware & Auth'],
    projectSuggestions: [
      { title: 'Headless E-Commerce Platform', desc: 'Next.js App Router store with Stripe checkout and incremental regeneration.', complexity: 'Advanced' },
      { title: 'AI-Powered Documentation Hub', desc: 'MDX-powered doc site with semantic vector search and dark mode.', complexity: 'Intermediate' },
    ],
    interviewTopics: ['App Router architecture vs Pages Router', 'Server Components data fetching waterfall elimination', 'Next.js Caching lifecycle (Request Memoization, Data Cache, Full Route Cache)', 'Middleware security patterns'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#ffffff',
  },

  // ─── 3. BACKEND ──────────────────────────────────────────────
  {
    id: 'nodejs',
    name: 'Node.js',
    category: 'Backend',
    relevance: {
      score: 94,
      status: 'Industry Standard',
      growth: '+20% YoY',
      openings: '230k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['JavaScript', 'HTTP/REST Fundamentals', 'Asynchronous Programming'],
    estimatedLearningTime: '6–8 weeks',
    careerRelevance: 'Powering microservices, APIs, and real-time backend systems at high concurrency.',
    relatedJobs: ['Node.js Backend Engineer', 'Full Stack Developer', 'API Platform Engineer'],
    skillsRequired: ['Event-driven non-blocking I/O', 'Streams & Buffers', 'Clustering & Worker Threads', 'Authentication (JWT, OAuth)'],
    projectSuggestions: [
      { title: 'High-Scale Chat & Video Gateway', desc: 'Socket.io and WebRTC signaling server with Redis Pub/Sub clustering.', complexity: 'Advanced' },
      { title: 'File Processing Pipeline', desc: 'Streaming audio/video transcoder utilizing Node worker threads.', complexity: 'Intermediate' },
    ],
    interviewTopics: ['Node.js Event Loop phases (timers, poll, check)', 'Backpressure handling in Node Streams', 'Memory leak detection with heapdump', 'Clustering vs Worker Threads'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#22c55e',
  },
  {
    id: 'fastapi',
    name: 'FastAPI',
    category: 'Backend',
    relevance: {
      score: 93,
      status: 'Surging Demand',
      growth: '+52% YoY',
      openings: '120k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['Python 3.10+', 'AsyncIO', 'RESTful API Design'],
    estimatedLearningTime: '3–5 weeks',
    careerRelevance: 'The premier framework for serving AI/ML models, high-performance Python microservices, and modern APIs.',
    relatedJobs: ['AI Backend Developer', 'Python API Engineer', 'Machine Learning Platform Engineer'],
    skillsRequired: ['Pydantic v2 validation', 'Async route handlers', 'Dependency Injection system', 'OpenAPI / Swagger auto-generation'],
    projectSuggestions: [
      { title: 'LLM Inference Gateway API', desc: 'Streaming tokens with SSE, token-bucket rate limiting, and API key billing.', complexity: 'Advanced' },
      { title: 'IoT Sensor Telemetry Collector', desc: 'High-throughput async ingestion service with Redis buffering.', complexity: 'Intermediate' },
    ],
    interviewTopics: ['Pydantic v2 Rust core performance benefits', 'Dependency Injection lifecycle in FastAPI', 'Background tasks vs Celery queues', 'Streaming responses with AsyncGenerators'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#06b6d4',
  },
  {
    id: 'flask',
    name: 'Flask',
    category: 'Backend',
    relevance: {
      score: 83,
      status: 'Industry Standard',
      growth: '+8% YoY',
      openings: '85k+ global openings',
    },
    level: 'Beginner',
    prerequisites: ['Python basics', 'HTML/HTTP basics'],
    estimatedLearningTime: '3–4 weeks',
    careerRelevance: 'Lightweight micro-framework great for quick prototyping, internal tools, and legacy Python services.',
    relatedJobs: ['Python Developer', 'Junior Backend Engineer'],
    skillsRequired: ['WSGI request context', 'Blueprints architecture', 'Jinja2 templating', 'SQLAlchemy integration'],
    projectSuggestions: [
      { title: 'Internal Operations Dashboard', desc: 'Admin panel with role-based access control and CSV reporting.', complexity: 'Intermediate' },
    ],
    interviewTopics: ['Application Context vs Request Context', 'Thread locals in Flask', 'WSGI vs ASGI protocols'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#94a3b8',
  },
  {
    id: 'springboot',
    name: 'Spring Boot',
    category: 'Backend',
    relevance: {
      score: 92,
      status: 'Industry Standard',
      growth: '+18% YoY',
      openings: '260k+ global openings',
    },
    level: 'Advanced',
    prerequisites: ['Core Java', 'OOP Principles', 'Relational Databases'],
    estimatedLearningTime: '8–12 weeks',
    careerRelevance: 'The dominant enterprise Java microservices framework trusted by Fortune 500 corporations.',
    relatedJobs: ['Enterprise Java Architect', 'Backend Staff Engineer', 'Cloud Microservices Developer'],
    skillsRequired: ['Spring Dependency Injection & IoC', 'Spring Data JPA & Hibernate', 'Spring Security & OAuth2', 'Spring Cloud & Kafka'],
    projectSuggestions: [
      { title: 'Distributed Banking Microservices', desc: 'CQRS and Event Sourcing payment processor with Spring Cloud & Eureka.', complexity: 'Advanced' },
      { title: 'Multi-Factor Auth Service', desc: 'Enterprise OAuth2 Authorization Server with biometric webauthn.', complexity: 'Advanced' },
    ],
    interviewTopics: ['Spring Bean lifecycles & scopes', 'Transactional propagation levels in Spring', 'N+1 query problem in Hibernate JPA', 'Spring WebFlux reactive programming'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#65a30d',
  },

  // ─── 4. DATABASE ─────────────────────────────────────────────
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'Database',
    relevance: {
      score: 98,
      status: 'Industry Standard',
      growth: '+35% YoY',
      openings: '290k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['Relational Database Basics', 'Basic SQL queries'],
    estimatedLearningTime: '4–6 weeks',
    careerRelevance: 'The most versatile, powerful, and beloved open-source SQL database in modern software.',
    relatedJobs: ['Database Administrator', 'Backend Engineer', 'Data Platform Engineer'],
    skillsRequired: ['Complex Joins & Window Functions', 'B-Tree & GIN Indexing', 'JSONB semi-structured storage', 'pgvector & full-text search'],
    projectSuggestions: [
      { title: 'Hybrid Relational + Vector Search Store', desc: 'PostgreSQL with pgvector for semantic retrieval alongside relational user data.', complexity: 'Advanced' },
      { title: 'High-Volume Financial Ledger', desc: 'ACID-compliant double-entry ledger with row-level locking and audit triggers.', complexity: 'Intermediate' },
    ],
    interviewTopics: ['MVCC (Multi-Version Concurrency Control) & VACUUM', 'Query Planner EXPLAIN ANALYZE interpretation', 'Index types (B-Tree, Hash, GIN, GiST)', 'Connection pooling and transaction isolation levels'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#334155',
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    category: 'Database',
    relevance: {
      score: 87,
      status: 'High Demand',
      growth: '+16% YoY',
      openings: '160k+ global openings',
    },
    level: 'Beginner',
    prerequisites: ['JSON notation', 'Basic Database Knowledge'],
    estimatedLearningTime: '3–4 weeks',
    careerRelevance: 'Popular document-oriented NoSQL database for flexible schemas, rapid prototyping, and event storage.',
    relatedJobs: ['Full Stack Developer (MERN)', 'NoSQL Database Specialist'],
    skillsRequired: ['BSON Document Modeling', 'Aggregation Pipeline', 'Replica Sets & Sharding', 'Indexing Strategies'],
    projectSuggestions: [
      { title: 'Content Management Catalog', desc: 'Flexible schema CMS handling diverse product attributes and versioning.', complexity: 'Intermediate' },
    ],
    interviewTopics: ['Document schema design patterns vs embedding', 'MongoDB Aggregation Pipeline stages', 'Write Concerns and Read Preferences', 'WiredTiger storage engine locking'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#10b981',
  },
  {
    id: 'redis',
    name: 'Redis',
    category: 'Database',
    relevance: {
      score: 94,
      status: 'Industry Standard',
      growth: '+30% YoY',
      openings: '210k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['Key-value storage concepts', 'Network caching concepts'],
    estimatedLearningTime: '2–3 weeks',
    careerRelevance: 'In-memory data store essential for caching, session management, rate-limiting, and Pub/Sub.',
    relatedJobs: ['System Architect', 'Senior Backend Engineer', 'Performance Engineer'],
    skillsRequired: ['Data Structures (Hashes, Sorted Sets, Bitmaps)', 'Pub/Sub & Redis Streams', 'Cache Eviction Policies (LRU, LFU)', 'Persistence (RDB, AOF)'],
    projectSuggestions: [
      { title: 'Distributed Rate Limiter & Leaderboard', desc: 'Sliding-window rate limiter and live gaming leaderboard using Sorted Sets.', complexity: 'Intermediate' },
    ],
    interviewTopics: ['Redis single-threaded event model vs multi-threading', 'Cache-aside vs Write-through vs Write-behind', 'Handling cache stampede and cache penetration', 'RDB vs AOF persistence trade-offs'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#ef4444',
  },

  // ─── 5. CLOUD ────────────────────────────────────────────────
  {
    id: 'aws',
    name: 'AWS',
    category: 'Cloud',
    relevance: {
      score: 97,
      status: 'Industry Standard',
      growth: '+32% YoY',
      openings: '340k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['Networking fundamentals (VPC, DNS, Subnets)', 'Linux basics'],
    estimatedLearningTime: '8–12 weeks',
    careerRelevance: 'Market-leading cloud provider powering the majority of modern web applications.',
    relatedJobs: ['AWS Cloud Architect', 'DevOps Cloud Engineer', 'Infrastructure Specialist'],
    skillsRequired: ['Compute (EC2, Lambda, ECS)', 'Storage & DB (S3, RDS, DynamoDB)', 'Networking (VPC, Route53, CloudFront)', 'Security & IAM Policies'],
    projectSuggestions: [
      { title: 'Serverless Video Processing Pipeline', desc: 'S3 upload trigger -> Lambda transcoder -> DynamoDB metadata -> CloudFront CDN.', complexity: 'Advanced' },
      { title: 'Multi-Tier Resilient VPC', desc: 'Terraform-provisioned public/private subnets, NAT Gateways, and Auto-scaling groups.', complexity: 'Advanced' },
    ],
    interviewTopics: ['IAM Least Privilege & Role Assumption', 'Well-Architected Framework 6 Pillars', 'S3 consistency model', 'DynamoDB partition key design & GSI hot partitioning'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#f59e0b',
  },
  {
    id: 'azure',
    name: 'Azure',
    category: 'Cloud',
    relevance: {
      score: 91,
      status: 'High Demand',
      growth: '+26% YoY',
      openings: '220k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['Cloud basics', 'Active Directory / Identity concepts'],
    estimatedLearningTime: '8–10 weeks',
    careerRelevance: 'Crucial for enterprise cloud infrastructure, Microsoft environments, and Azure OpenAI integrations.',
    relatedJobs: ['Azure Cloud Engineer', 'Enterprise Solutions Architect'],
    skillsRequired: ['Entra ID (Azure AD)', 'App Services & Azure Functions', 'Azure Kubernetes Service (AKS)', 'Cosmos DB'],
    projectSuggestions: [
      { title: 'Enterprise Single Sign-On Gateway', desc: 'Entra ID SAML/OAuth2 auth portal with conditional access policies.', complexity: 'Intermediate' },
    ],
    interviewTopics: ['Entra ID role assignments & service principals', 'Cosmos DB consistency levels (5 levels)', 'Azure Resource Manager (ARM) vs Bicep'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#0284c7',
  },
  {
    id: 'gcp',
    name: 'Google Cloud',
    category: 'Cloud',
    relevance: {
      score: 89,
      status: 'High Demand',
      growth: '+28% YoY',
      openings: '160k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['Cloud basics', 'Containers & Kubernetes'],
    estimatedLearningTime: '6–8 weeks',
    careerRelevance: 'Preferred cloud for Big Data analytics, AI/ML Vertex AI solutions, and Google Kubernetes Engine.',
    relatedJobs: ['GCP Cloud Engineer', 'Data Platform Engineer', 'MLOps Specialist'],
    skillsRequired: ['Google Kubernetes Engine (GKE)', 'BigQuery & Dataflow', 'Vertex AI & Cloud Run', 'Cloud IAM'],
    projectSuggestions: [
      { title: 'Real-Time Streaming Analytics', desc: 'Pub/Sub -> Dataflow -> BigQuery streaming dashboard.', complexity: 'Advanced' },
    ],
    interviewTopics: ['BigQuery partitioning and clustering cost optimizations', 'Cloud Run serverless containers', 'VPC Service Controls'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#ea4335',
  },

  // ─── 6. DEVOPS ───────────────────────────────────────────────
  {
    id: 'docker',
    name: 'Docker',
    category: 'DevOps',
    relevance: {
      score: 96,
      status: 'Industry Standard',
      growth: '+24% YoY',
      openings: '280k+ global openings',
    },
    level: 'Beginner',
    prerequisites: ['Command-line CLI', 'Linux basics'],
    estimatedLearningTime: '2–3 weeks',
    careerRelevance: 'Universal containerization standard required in almost every modern software development role.',
    relatedJobs: ['DevOps Engineer', 'Backend Developer', 'Platform Engineer'],
    skillsRequired: ['Dockerfile optimization', 'Multi-stage builds', 'Docker Compose orchestration', 'Networking & Volume persistence'],
    projectSuggestions: [
      { title: 'Production Multi-Service Compose Stack', desc: 'Next.js + Node API + Postgres + Redis with health checks and volume management.', complexity: 'Intermediate' },
    ],
    interviewTopics: ['Linux namespaces and cgroups foundation', 'Layer caching and multi-stage build size minimization', 'CMD vs ENTRYPOINT differences', 'Rootless containers and security scanning'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#0ea5e9',
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    category: 'DevOps',
    relevance: {
      score: 95,
      status: 'Surging Demand',
      growth: '+36% YoY',
      openings: '210k+ global openings',
    },
    level: 'Advanced',
    prerequisites: ['Docker', 'Networking & DNS', 'Distributed Systems'],
    estimatedLearningTime: '8–12 weeks',
    careerRelevance: 'The undisputed gold standard for automating deployment, scaling, and management of containerized apps.',
    relatedJobs: ['Kubernetes Administrator (CKA)', 'Platform Engineer', 'Site Reliability Engineer (SRE)'],
    skillsRequired: ['Pods, Deployments, Services, Ingress', 'ConfigMaps, Secrets, PersistentVolumes', 'Helm Charts & Kustomize', 'Horizontal Pod Autoscaling (HPA) & CRDs'],
    projectSuggestions: [
      { title: 'Zero-Downtime Microservices Cluster', desc: 'Canary & Blue/Green deployments managed by ArgoCD GitOps on Kubernetes.', complexity: 'Advanced' },
    ],
    interviewTopics: ['Kubernetes Control Plane components (etcd, API server, Scheduler, Controller)', 'Pod lifecycle and probes (liveness, readiness, startup)', 'Service types (ClusterIP, NodePort, LoadBalancer)', 'Network policies and ingress controllers'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#3b82f6',
  },
  {
    id: 'terraform',
    name: 'Terraform',
    category: 'DevOps',
    relevance: {
      score: 92,
      status: 'High Demand',
      growth: '+29% YoY',
      openings: '170k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['Cloud Provider basics (AWS/GCP/Azure)', 'Infrastructure Concepts'],
    estimatedLearningTime: '4–6 weeks',
    careerRelevance: 'The premier Infrastructure as Code (IaC) tool for declarative cloud provisioning.',
    relatedJobs: ['Cloud DevOps Engineer', 'Infrastructure as Code Specialist'],
    skillsRequired: ['HCL (HashiCorp Config Language)', 'State Management & Remote Backends', 'Modular Reusable Architecture', 'Terraform Workspaces & Drift Detection'],
    projectSuggestions: [
      { title: 'Complete Cloud VPC & EKS Cluster', desc: 'End-to-end production AWS infrastructure codified with Terraform modules.', complexity: 'Advanced' },
    ],
    interviewTopics: ['Terraform State locking and remote backend security', 'Managing infrastructure drift and `terraform import`', 'Count vs For_each loops in modules', 'Terraform plan vs apply execution lifecycle'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#8b5cf6',
  },
  {
    id: 'cicd',
    name: 'CI/CD',
    category: 'DevOps',
    relevance: {
      score: 95,
      status: 'Industry Standard',
      growth: '+25% YoY',
      openings: '290k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['Git & Version Control', 'Automated Testing basics'],
    estimatedLearningTime: '3–4 weeks',
    careerRelevance: 'Automated continuous integration and deployment pipelines ensure rapid, secure, reliable releases.',
    relatedJobs: ['Build & Release Engineer', 'DevOps Specialist', 'Software Engineer'],
    skillsRequired: ['GitHub Actions / GitLab CI', 'Automated Test Runners & Linters', 'Security Scanning (SAST/DAST)', 'Artifact Registries & Release Tagging'],
    projectSuggestions: [
      { title: 'Enterprise CI/CD GitHub Actions Pipeline', desc: 'Lint -> Unit Test -> Docker Build -> Trivy Security Scan -> Deploy to Staging.', complexity: 'Intermediate' },
    ],
    interviewTopics: ['Continuous Delivery vs Continuous Deployment', 'Secrets management in pipeline runners', 'Matrix builds and caching strategies', 'GitOps deployment pattern with ArgoCD'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#10b981',
  },

  // ─── 7. AI/ML ────────────────────────────────────────────────
  {
    id: 'machine-learning',
    name: 'Machine Learning',
    category: 'AI/ML',
    relevance: {
      score: 96,
      status: 'High Demand',
      growth: '+38% YoY',
      openings: '220k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['Python', 'Linear Algebra & Statistics', 'NumPy & Pandas'],
    estimatedLearningTime: '10–14 weeks',
    careerRelevance: 'Fundamental bedrock powering modern predictive models, classifiers, and recommendation engines.',
    relatedJobs: ['Machine Learning Engineer', 'Data Scientist', 'Quantitative Researcher'],
    skillsRequired: ['Supervised & Unsupervised Learning', 'Feature Engineering & Cross-Validation', 'Scikit-Learn & XGBoost', 'Model Metrics (AUC, F1-Score, RMSE)'],
    projectSuggestions: [
      { title: 'Customer Churn Predictor & Explainer', desc: 'XGBoost classifier with SHAP explainability values and REST prediction API.', complexity: 'Intermediate' },
    ],
    interviewTopics: ['Bias-Variance Tradeoff & Regularization (L1/L2)', 'Gradient Boosting vs Random Forest', 'Handling class imbalance (SMOTE, Focal Loss)', 'Precision-Recall trade-offs'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#a855f7',
  },
  {
    id: 'deep-learning',
    name: 'Deep Learning',
    category: 'AI/ML',
    relevance: {
      score: 95,
      status: 'High Demand',
      growth: '+40% YoY',
      openings: '190k+ global openings',
    },
    level: 'Advanced',
    prerequisites: ['Machine Learning', 'Multivariable Calculus', 'PyTorch or TensorFlow'],
    estimatedLearningTime: '12–16 weeks',
    careerRelevance: 'Powering computer vision, speech synthesis, autonomous vehicles, and neural architectures.',
    relatedJobs: ['Deep Learning Researcher', 'Computer Vision Specialist', 'NLP Engineer'],
    skillsRequired: ['Backpropagation & Optimizers (AdamW)', 'CNNs & Vision Transformers', 'Attention Mechanisms', 'Loss Functions & Learning Rate Schedulers'],
    projectSuggestions: [
      { title: 'Real-time Object Segmentation & Tracking', desc: 'YOLOv8 model fine-tuned on custom industrial dataset with ONNX export.', complexity: 'Advanced' },
    ],
    interviewTopics: ['Vanishing and Exploding Gradient solutions', 'Dropout & Batch Normalization mechanics', 'Self-Attention computational complexity O(N²)', 'Quantization and FP16 Mixed Precision'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#ec4899',
  },
  {
    id: 'pytorch',
    name: 'PyTorch',
    category: 'AI/ML',
    relevance: {
      score: 97,
      status: 'Surging Demand',
      growth: '+50% YoY',
      openings: '180k+ global openings',
    },
    level: 'Advanced',
    prerequisites: ['Python', 'Deep Learning Concepts'],
    estimatedLearningTime: '6–8 weeks',
    careerRelevance: 'The undisputed favorite framework in modern AI research, academia, and generative AI companies.',
    relatedJobs: ['AI Research Engineer', 'PyTorch Model Developer', 'Foundation Model Trainer'],
    skillsRequired: ['Tensors & Autograd', 'torch.nn.Module architecture', 'Custom Datasets & DataLoaders', 'Distributed Data Parallel (DDP)'],
    projectSuggestions: [
      { title: 'Custom Transformer Architecture from Scratch', desc: 'Multi-head attention and decoder layers coded from mathematical first principles.', complexity: 'Advanced' },
    ],
    interviewTopics: ['Dynamic computational graph vs Static graph', 'Autograd computational graph tracking (`requires_grad`)', 'DDP vs FSDP (Fully Sharded Data Parallel)', 'GPU memory management and CUDA out-of-memory debugging'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#f97316',
  },
  {
    id: 'tensorflow',
    name: 'TensorFlow',
    category: 'AI/ML',
    relevance: {
      score: 84,
      status: 'Industry Standard',
      growth: '+5% YoY',
      openings: '120k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['Python', 'Machine Learning basics'],
    estimatedLearningTime: '6–8 weeks',
    careerRelevance: 'Widely deployed in Google ecosystem and embedded production environments (TF Lite, TF Serving).',
    relatedJobs: ['Production ML Engineer', 'Edge AI Developer'],
    skillsRequired: ['Keras Sequential & Functional APIs', 'TF Serving & Model Export', 'TensorFlow Lite for Mobile/IoT', 'TensorBoard visualization'],
    projectSuggestions: [
      { title: 'Mobile Edge Vision Classifier', desc: 'TF Lite model quantized for mobile runtime.', complexity: 'Intermediate' },
    ],
    interviewTopics: ['TensorFlow Serving model signature definitions', 'Keras Custom Callbacks', 'Static computation graphs with @tf.function'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#ea580c',
  },

  // ─── 8. GENERATIVE AI ────────────────────────────────────────
  {
    id: 'generative-ai',
    name: 'Generative AI',
    category: 'Generative AI',
    relevance: {
      score: 99,
      status: 'Emerging Frontier',
      growth: '+125% YoY',
      openings: '250k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['Python', 'NLP basics', 'API integration'],
    estimatedLearningTime: '6–10 weeks',
    careerRelevance: 'The fastest-growing technological revolution in decades, commanding top-tier compensation.',
    relatedJobs: ['Generative AI Engineer', 'AI Solutions Architect', 'Chief AI Officer Advisor'],
    skillsRequired: ['Prompt Engineering & System Prompting', 'Structured Outputs (JSON Schema)', 'Multimodal Vision & Audio generation', 'Evaluation Metrics & Red Teaming'],
    projectSuggestions: [
      { title: 'Automated Code Review & Security Copilot', desc: 'Multi-stage GenAI bot scanning PRs for logic bugs and compliance.', complexity: 'Advanced' },
    ],
    interviewTopics: ['Temperature, Top-P, and Top-K sampling mechanics', 'Hallucination mitigation strategies', 'Few-shot vs Chain-of-Thought prompting', 'Model Alignment (RLHF, DPO)'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#d946ef',
  },
  {
    id: 'llms',
    name: 'LLMs',
    category: 'Generative AI',
    relevance: {
      score: 99,
      status: 'Surging Demand',
      growth: '+110% YoY',
      openings: '230k+ global openings',
    },
    level: 'Advanced',
    prerequisites: ['Python', 'Deep Learning', 'PyTorch'],
    estimatedLearningTime: '8–12 weeks',
    careerRelevance: 'Powering every major conversational interface, translation system, and autonomous knowledge worker.',
    relatedJobs: ['LLM Engineer', 'Foundation Model Specialist', 'Fine-tuning Architect'],
    skillsRequired: ['Transformer Decoders', 'Tokenization (BPE, WordPiece)', 'Fine-tuning (LoRA, QLoRA)', 'Inference Optimization (vLLM, TensorRT-LLM)'],
    projectSuggestions: [
      { title: 'Domain-Specific LLM Fine-Tuning', desc: 'LoRA fine-tuning of open-weights LLM on legal contracts with evaluation benchmarks.', complexity: 'Advanced' },
    ],
    interviewTopics: ['Rotary Position Embedding (RoPE) vs Absolute Embeddings', 'LoRA low-rank matrix decomposition math', 'FlashAttention memory access optimizations', 'KV Cache memory consumption calculations'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#8b5cf6',
  },
  {
    id: 'rag',
    name: 'RAG',
    category: 'Generative AI',
    relevance: {
      score: 98,
      status: 'Surging Demand',
      growth: '+95% YoY',
      openings: '210k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['Python', 'Vector Databases', 'LLM APIs'],
    estimatedLearningTime: '4–6 weeks',
    careerRelevance: 'The #1 enterprise architecture for grounding LLMs in proprietary enterprise data without fine-tuning.',
    relatedJobs: ['RAG Specialist', 'AI Application Developer', 'Enterprise Knowledge Architect'],
    skillsRequired: ['Chunking Strategies (Semantic, Recursive)', 'Embedding Models & Distance Metrics', 'Hybrid Search (Dense + BM25 Sparse)', 'Reranking & Context Compression'],
    projectSuggestions: [
      { title: 'Enterprise Knowledge Assistant with Hybrid RAG', desc: 'End-to-end question answerer over 50,000 PDF documents with Cohere reranking.', complexity: 'Advanced' },
    ],
    interviewTopics: ['Lost in the Middle phenomenon in RAG context', 'Self-RAG and Corrective RAG (CRAG) patterns', 'Chunk size vs Retrieval recall tradeoff', 'RAG evaluation frameworks (RAGAS: Faithfulness, Answer Relevance)'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#06b6d4',
  },
  {
    id: 'ai-agents',
    name: 'AI Agents',
    category: 'Generative AI',
    relevance: {
      score: 99,
      status: 'Emerging Frontier',
      growth: '+140% YoY',
      openings: '190k+ global openings',
    },
    level: 'Advanced',
    prerequisites: ['LLMs & Prompting', 'Python', 'Tool Calling & APIs'],
    estimatedLearningTime: '6–8 weeks',
    careerRelevance: 'The frontier of autonomous software development—agents that plan, use tools, loop, and execute complex workflows.',
    relatedJobs: ['AI Agent Engineer', 'Autonomous Systems Developer', 'Cognitive Architecture Lead'],
    skillsRequired: ['ReAct (Reasoning + Acting) loops', 'Function/Tool Calling schema', 'Multi-Agent Orchestration (LangGraph, CrewAI)', 'Long-term Memory & Reflection'],
    projectSuggestions: [
      { title: 'Autonomous Competitive Intelligence Agent', desc: 'Multi-agent system searching web, synthesizing financial reports, and filing summaries.', complexity: 'Advanced' },
    ],
    interviewTopics: ['ReAct prompting pattern mechanics', 'Loop prevention and error recovery in autonomous agents', 'State graph management in LangGraph', 'Security guardrails for executing external tools'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#f43f5e',
  },
  {
    id: 'vector-databases',
    name: 'Vector Databases',
    category: 'Generative AI',
    relevance: {
      score: 95,
      status: 'Surging Demand',
      growth: '+85% YoY',
      openings: '160k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['Embedding concepts', 'Database fundamentals'],
    estimatedLearningTime: '3–4 weeks',
    careerRelevance: 'Critical infrastructure storing high-dimensional embeddings for similarity search, recommendation, and RAG.',
    relatedJobs: ['Vector Search Engineer', 'AI Infrastructure Developer'],
    skillsRequired: ['HNSW (Hierarchical Navigable Small World)', 'Cosine vs Dot Product vs Euclidean distance', 'Metadata Filtering', 'Pinecone, Qdrant, Chroma, Milvus'],
    projectSuggestions: [
      { title: 'Multimodal Image-Text Search Engine', desc: 'CLIP embeddings stored in Qdrant enabling natural language photo search.', complexity: 'Intermediate' },
    ],
    interviewTopics: ['HNSW graph traversal vs Inverted File (IVF) index', 'Curse of Dimensionality in vector search', 'Pre-filtering vs Post-filtering performance implications'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#14b8a6',
  },

  // ─── 9. DATA ENGINEERING ─────────────────────────────────────
  {
    id: 'apache-spark',
    name: 'Apache Spark',
    category: 'Data Engineering',
    relevance: {
      score: 93,
      status: 'Industry Standard',
      growth: '+20% YoY',
      openings: '210k+ global openings',
    },
    level: 'Advanced',
    prerequisites: ['Python / Scala', 'Distributed Computing concepts', 'SQL'],
    estimatedLearningTime: '8–10 weeks',
    careerRelevance: 'The undisputed unified analytics engine for large-scale distributed data processing.',
    relatedJobs: ['Big Data Engineer', 'Data Platform Architect', 'Spark Specialist'],
    skillsRequired: ['PySpark DataFrames & SQL', 'RDDs & DAG execution plan', 'Spark Structured Streaming', 'Memory Tuning & Partition Skew'],
    projectSuggestions: [
      { title: 'Petabyte-Scale Clickstream Aggregator', desc: 'PySpark streaming pipeline on Databricks with Delta Lake lakehouse architecture.', complexity: 'Advanced' },
    ],
    interviewTopics: ['Transformations (Narrow vs Wide) and Shuffling', 'Spark Memory Management (Storage vs Execution)', 'Tuning data skew with salting', 'Broadcast joins vs Sort-Merge joins'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#f97316',
  },
  {
    id: 'airflow',
    name: 'Airflow',
    category: 'Data Engineering',
    relevance: {
      score: 91,
      status: 'Industry Standard',
      growth: '+22% YoY',
      openings: '170k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['Python', 'ETL concepts', 'Cron / Scheduling'],
    estimatedLearningTime: '4–6 weeks',
    careerRelevance: 'The standard platform to author, schedule, and monitor batch workflows and data pipelines programmatically.',
    relatedJobs: ['Data Pipeline Engineer', 'Data Ops Engineer'],
    skillsRequired: ['DAG (Directed Acyclic Graph) design', 'TaskFlow API & Operators', 'XComs & Variables', 'Celery & Kubernetes Executors'],
    projectSuggestions: [
      { title: 'Automated Daily Data Lakehouse Ingestion', desc: 'Multi-stage Airflow DAG extracting APIs, validating with Great Expectations, and loading Snowflake.', complexity: 'Intermediate' },
    ],
    interviewTopics: ['Airflow Scheduler architectural bottleneck prevention', 'XCom data size limitations and best practices', 'Dynamic DAG generation patterns', 'Idempotency in pipeline design'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#06b6d4',
  },

  // ─── 10. CYBERSECURITY ───────────────────────────────────────
  {
    id: 'cybersecurity',
    name: 'Cybersecurity',
    category: 'Cybersecurity',
    relevance: {
      score: 96,
      status: 'Surging Demand',
      growth: '+42% YoY',
      openings: '320k+ global openings',
    },
    level: 'Intermediate',
    prerequisites: ['Computer Networks (TCP/IP)', 'Linux', 'Web Security Basics'],
    estimatedLearningTime: '10–14 weeks',
    careerRelevance: 'Critical defense safeguarding infrastructure, data integrity, and compliance in every modern company.',
    relatedJobs: ['Security Engineer', 'AppSec Specialist', 'Penetration Tester', 'SOC Analyst'],
    skillsRequired: ['OWASP Top 10 vulnerabilities', 'Cryptography & Public Key Infrastructure (PKI)', 'Zero Trust Architecture', 'Threat Modeling & SIEM Monitoring'],
    projectSuggestions: [
      { title: 'Automated Vulnerability & Secrets Scanner', desc: 'CLI tool scanning GitHub repos for leaked API keys, tokens, and insecure dependencies.', complexity: 'Intermediate' },
    ],
    interviewTopics: ['OWASP Top 10 mitigation strategies', 'Symmetric vs Asymmetric Encryption & TLS 1.3 Handshake', 'CORS, CSRF, and XSS attack vectors and defense', 'Zero Trust principles in cloud architecture'],
    practiceAvailability: { practiceTests: true, codeSandbox: true, mockInterviews: true, flashcards: true },
    color: '#e11d48',
  },
]

// ─── User Current Practice Stack (Initial Defaults) ────────────
const DEFAULT_USER_PRACTICE_STACK = [
  {
    id: 'python',
    name: 'Python',
    progress: 84,
    currentLevel: 'Level 4: Advanced',
    practiceScore: 84,
    testsCompleted: 18,
    lastTest: 'Yesterday',
    bestScore: 96,
    starsEarned: 4,
    color: '#38bdf8',
    category: 'Programming',
  },
  {
    id: 'react',
    name: 'React',
    progress: 90,
    currentLevel: 'Level 5: Master',
    practiceScore: 92,
    testsCompleted: 24,
    lastTest: 'Today',
    bestScore: 98,
    starsEarned: 5,
    color: '#60a5fa',
    category: 'Frontend',
  },
  {
    id: 'postgresql',
    name: 'SQL',
    progress: 82,
    currentLevel: 'Level 4: Advanced',
    practiceScore: 86,
    testsCompleted: 15,
    lastTest: '2 days ago',
    bestScore: 94,
    starsEarned: 4,
    color: '#a855f7',
    category: 'Database',
  },
  {
    id: 'docker',
    name: 'Docker',
    progress: 75,
    currentLevel: 'Level 3: Intermediate',
    practiceScore: 78,
    testsCompleted: 10,
    lastTest: '4 days ago',
    bestScore: 88,
    starsEarned: 3,
    color: '#0ea5e9',
    category: 'DevOps',
  },
]

/**
 * Fetch complete roadmap dataset: all categorized technologies and user's current practice stack.
 */
export async function fetchRoadmapData() {
  await new Promise((r) => setTimeout(r, 300))

  // Retrieve any user customizations from localStorage if present
  const savedStack = localStorage.getItem('ai_career_user_practice_stack')
  const currentStack = savedStack ? JSON.parse(savedStack) : DEFAULT_USER_PRACTICE_STACK

  return {
    categories: TECH_CATEGORIES,
    relevanceFilters: RELEVANCE_FILTERS,
    technologies: MOCK_ALL_TECHNOLOGIES,
    userPracticeStack: currentStack,
  }
}

/**
 * Persist updated practice stack
 */
export async function saveUserPracticeStack(stack) {
  await new Promise((r) => setTimeout(r, 100))
  localStorage.setItem('ai_career_user_practice_stack', JSON.stringify(stack))
  return stack
}
